id: 623ecc21a2664bb6a1592a04d976f9fa
initial_creation_type: ocr
created_date: 28/10/2021
updated_date: 28/10/2021
source_metadata:
  title: འཕགས་པ་སྒྱུ་མ་མཁན་བཟང་པོ་ལུང་བསྟན་པ་ཞེས་བྱ་བ་ཐེག་པ་ཆེན་པོའི་མདོ།
  source_id: W22083
  initial_creation_type: ocr
  org: bdrc
  volumes:
    7ffafca54d5e4c26b519a35941b65b57:
      base_file: v039.txt
      image_group_id: I3746
      title: ''
      total_pages: 100
      volume_number: 39
vol2fn:
  v039: v039.txt
